version: "3.9"

services:
  ghost:
    image: "ghost:5.19"
    ports:
      - 2368:2368
    volumes:
      - ../content:/var/lib/ghost/content
    environment:
      NODE_ENV: development
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost-local.db
  devcontainer:
    build: .
    # Bind workspace onto /workspace
    volumes:
      - ..:/workspace:cached
    # Prevent container from exiting
    command: sleep infinity
    # Allow calls to `localhost`
    network_mode: "host"