name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout theme
      run: git clone --branch master https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/dunnkers/ghost-dunnkers-theme-edition.git content/themes/dunnkers-theme-edition

    - name: Start Ghost Container
      run: |
        docker run -d --name ghost -p 2368:2368 \
          -v ${{ github.workspace }}/content:/var/lib/ghost/content \
          --env NODE_ENV=development \
          --env database__client=sqlite3 \
          --env database__connection__filename=/var/lib/ghost/content/data/ghost-local.db \
          --env url=http://localhost:2368 \
          ghost:5.126.1

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install -g ghost-static-site-generator gh-pages replace-in-file

    - name: Wait for Ghost to be ready
      run: |
        echo "Waiting for Ghost to start..."
        sleep 10
        # Use curl to check if Ghost is up and running
        until curl -s http://localhost:2368 > /dev/null; do
          echo "Ghost is unavailable - sleeping"
          sleep 5
        done
        echo "Ghost is up and running"

    - name: Build
      run: gssg && npx replace-in-file --configFile=replace-in-file_config.json && npx replace-in-file --configFile=replace-in-file_sitemap_config.json && npx replace-in-file --configFile=replace-in-file_sourcemaps_config.json

    - name: Create CNAME
      run: echo 'jeroenoverschie.nl' > static/CNAME

    - name: Deploy
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        npx gh-pages -d static --repo https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
